# Base de dados
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5433/${DB_NAME:berp_db}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Servidor
server.port=8081

# Hikari Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=300000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool-BERP-Dev

# Flyway
spring.flyway.locations=classpath:db/migration,classpath:db/testdata


# Logs
logging.level.org.springframework=INFO
logging.level.com.berp=DEBUG