spring.application.name=berp-api

# Config Jackson
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

# Lanca exception quando rota nao existe
spring.mvc.throw-exception-if-no-handler-found=true

# Perfil default
spring.profiles.active=dev

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect